emacs ./README.org  --batch -f org-md-export-to-markdown --kill
emacs ./setup_dependencies.org --batch -f org-md-export-to-markdown --kill
emacs ./testenv/README.org --batch -f org-md-export-to-markdown --kill
emacs ./setup-testlab/ansible/README.org --batch -f org-md-export-to-markdown --kill
emacs ./setup-testlab/create_vm_image.org --batch -f org-md-export-to-markdown --kill
emacs ./setup-testlab/README.org --batch -f org-md-export-to-markdown --kill
emacs ./setup-testlab/using_vm_image.org --batch -f org-md-export-to-markdown --kill
emacs ./setup-testlab/workarounds.org --batch -f org-md-export-to-markdown --kill
emacs ./common/README.org --batch -f org-md-export-to-markdown --kill
emacs ./basic-solutions/README.org --batch -f org-md-export-to-markdown --kill
emacs ./basic01-xdp-pass/README.org --batch -f org-md-export-to-markdown --kill
emacs ./basic02-prog-by-name/README.org --batch -f org-md-export-to-markdown --kill
./basic02-prog-by-name/xdp_offload_nfp.org --batch -f org-md-export-to-markdown emacs --kill
emacs ./basic03-map-counter/README.org --batch -f org-md-export-to-markdown --kill
emacs ./basic04-pinning-maps/README.org --batch -f org-md-export-to-markdown --kill
emacs ./tracing01-xdp-simple/README.org --batch -f org-md-export-to-markdown --kill
emacs ./tracing02-xdp-monitor/README.org --batch -f org-md-export-to-markdown --kill
./tracing03-xdp-debug-print/README.org --batch -f org-md-export-to-markdown emacs --kill
emacs ./tracing04-xdp-tcpdump/README.org --batch -f org-md-export-to-markdown --kill
emacs ./packet-solutions/README.org --batch -f org-md-export-to-markdown --kill
emacs ./packet01-parsing/README.org --batch -f org-md-export-to-markdown --kill
emacs ./packet02-rewriting/README.org --batch -f org-md-export-to-markdown --kill
emacs ./packet03-redirecting/README.org --batch -f org-md-export-to-markdown --kill
./advanced01-xdp-tc-interact/README.org --batch -f org-md-export-to-markdown emacs --kill
emacs ./advanced03-AF_XDP/README.org --batch -f org-md-export-to-markdown --kill
